### PR TITLE
Update terraform.yml

### PR DESCRIPTION
**Pull request by huyhua-nvg**
add missing type for inputs

### CODE REVIEW

**Comment by huyhua-nvg** [comment]
@1inuxoid gonna need your help on this again

**Comment by huyhua-nvg** [comment]
Actually let's keep this here until child workflow reliably passes.

**Comment by 1inuxoid** [comment]
You can actually refer to new workflows in branches too ;)

**Comment by 1inuxoid** [comment]
I'm on vacation till 02.01

**Pull request merged**
