### PR TITLE
SAFTS-210: Introducing GHAS code scanning (CodeQL).

### PR DESCRIPTION
**Pull request by smg-milves**
Setting up CodeQL configuration for code scanning as part of GHAS rollout effort. Please consult https://www.notion.so/smgnet/Static-Code-Analysis-110ae38191cc45ceaad9af7817ef7b92 for more details.

### CODE REVIEW

**Comment by huyhua-nvg** [comment]
@smg-milves is it needed? There's no code in this repo, only github workflows and actions.

**Comment by dym-ok** [comment]
Milon

> @smg-milves is it needed? There's no code in this repo, only github workflows and actions.

You were ahead, Huy 😄

**Comment by milves-s24** [comment]
Hi guys! I got the impression that this repo is hosting examples/templates for GH workflows, so I thought it might be beneficial to have CodeQL config in there as well. We can turn off triggers by commenting out _on_ section in the workflow to avoid scheduled runs... Let me know if I got it wrong and I'll ditch the PR :) Thanks, cheers!

**Comment by milves-s24** [comment]
Closing this one, going with the default setup... Cheers!

**Pull request closed without merging**
